"""initial_schema

Revision ID: 3839267a1d29
Revises: 
Create Date: 2026-04-24 16:24:31.663527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3839267a1d29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('bot_id', sa.String(length=64), nullable=True),
    sa.Column('created_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=320), nullable=True),
    sa.Column('acknowledged_at_ms', sa.BigInteger(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_bot_id'), ['bot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_created_at_ms'), ['created_at_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('actor_email', sa.String(length=320), nullable=False),
    sa.Column('actor_role', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=False),
    sa.Column('at_ms', sa.BigInteger(), nullable=False),
    sa.Column('diff', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_at_id', ['at_ms', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_actor_email'), ['actor_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_at_ms'), ['at_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_resource_type'), ['resource_type'], unique=False)

    op.create_table('bots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('owner_email', sa.String(length=320), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('active_config_version', sa.Integer(), nullable=True),
    sa.Column('created_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('updated_at_ms', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bots_owner_email'), ['owner_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_bots_state'), ['state'], unique=False)

    op.create_table('config_versions',
    sa.Column('bot_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=320), nullable=False),
    sa.Column('created_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('applied_at_ms', sa.BigInteger(), nullable=True),
    sa.Column('approved_by', sa.String(length=320), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=False),
    sa.Column('validation_warnings', sa.JSON(), nullable=False),
    sa.Column('parent_version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('bot_id', 'version')
    )
    with op.batch_alter_table('config_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_config_versions_status'), ['status'], unique=False)

    op.create_table('fills',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('bot_id', sa.String(length=64), nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('filled_at_ms', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fills_bot_id'), ['bot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fills_client_order_id'), ['client_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fills_filled_at_ms'), ['filled_at_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_fills_symbol'), ['symbol'], unique=False)

    op.create_table('orders',
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('bot_id', sa.String(length=64), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('adapter_id', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('notional', sa.Float(), nullable=True),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('broker_order_id', sa.String(length=128), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('submitted_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('client_order_id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_bot_id'), ['bot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_submitted_at_ms'), ['submitted_at_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_symbol'), ['symbol'], unique=False)

    op.create_table('positions',
    sa.Column('bot_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('updated_at_ms', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('bot_id', 'symbol')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('positions')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_symbol'))
        batch_op.drop_index(batch_op.f('ix_orders_submitted_at_ms'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_bot_id'))

    op.drop_table('orders')
    with op.batch_alter_table('fills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fills_symbol'))
        batch_op.drop_index(batch_op.f('ix_fills_filled_at_ms'))
        batch_op.drop_index(batch_op.f('ix_fills_client_order_id'))
        batch_op.drop_index(batch_op.f('ix_fills_bot_id'))

    op.drop_table('fills')
    with op.batch_alter_table('config_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_versions_status'))

    op.drop_table('config_versions')
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bots_state'))
        batch_op.drop_index(batch_op.f('ix_bots_owner_email'))

    op.drop_table('bots')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_at_ms'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_email'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))
        batch_op.drop_index('ix_audit_at_id')

    op.drop_table('audit_events')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at_ms'))
        batch_op.drop_index(batch_op.f('ix_alerts_bot_id'))

    op.drop_table('alerts')
    # ### end Alembic commands ###
